### PR TITLE
fix: preserve transaction state in $use, $unuse, and $unuseAll

### LINKED ISSUE #2494: $unuseAll() and $unuse() break transaction isolation
## Description

Calling `$unuseAll()` or `$unuse()` on a transaction client returns a new client that runs queries **outside** the active transaction.

## Reproduction

```ts
const client = new ZenStackClient(schema, {
  dialect: new PostgresDialect({ pool }),
  plugins: [new PolicyPlugin()],
});

await client.$transaction(async (tx) => {
  // Get txid inside the transaction
  const [{ txid: txTxid }] = await tx.$unuseAll().$queryRawUnsafe<{ txid: string }>(
    'SELECT txid_current() AS txid'
  );

  // Get txid via $unuseAll()
  const [{ txid: unuseTxid }] = await tx.$unuseAll().$queryRawUnsafe<{ txid: string }>(
    'SELECT txid_current() AS txid'
  );

  console.log('tx txid:', txTxid);
  console.log('$unuseAll() txid:', unuseTxid);
  // These are DIFFERENT — $unuseAll() escaped the transaction
});
```

Output:
```
tx txid: 17474959
$unuseAll() txid: 17474960
```

## Root cause

In `client-impl.ts`, `$unuseAll()` creates a new `ClientImpl` via `new ClientImpl(this.schema, newOptions, this)`. The constructor always runs `this.kysely = new Kysely(this.kyselyProps)` (line 131), which creates a fresh Kysely instance from `kyselyProps`.

However, when inside a transaction, the transaction state lives in `txClient.kysely` (set to the Kysely `Transaction` object on line 257 of `interactiveTransaction`). The `kyselyProps` don't carry the transaction context, so the new client gets a non-transactional connection.

The same issue applies to `$unuse()` and `$use()`.

## Suggested fix

After constructing the new client, propagate the transaction Kysely instance:

```ts
$unuseAll() {
    const newOptions = { ...this.options, plugins: [] };
    const newClient = new ClientImpl(this.schema, newOptions, this);
    newClient.inputValidator = new InputValidator(newClient, {
        enabled: newOptions.validateInput !== false,
    });
    // Preserve transaction state
    if (this.kysely.isTransaction) {
        newClient.kysely = this.kysely;
    }
    return newClient;
}
```

Same pattern for `$unuse()`, `$use()`, and `$setAuth()`.

## Version

`@zenstackhq/orm` 3.4.6

### PR DESCRIPTION
**Pull request by pkudinov**
Fixes #2494

## Problem

Calling `$use()`, `$unuse()`, or `$unuseAll()` on a transaction client returns a new client that runs queries **outside** the active transaction.

The constructor always creates a fresh Kysely instance from `kyselyProps` (`this.kysely = new Kysely(this.kyselyProps)`), but the transaction state lives in `txClient.kysely` which was set to the Kysely `Transaction` object after construction. The new client never receives this.

## Fix

After constructing the new client in `$use()`, `$unuse()`, and `$unuseAll()`, propagate the transaction Kysely instance:

```ts
if (this.kysely.isTransaction) {
    newClient.kysely = this.kysely;
}
```

## Tests

Three new tests in `tests/e2e/orm/client-api/transaction.test.ts` verify that `$unuseAll()`, `$unuse()`, and `$use()` on a transaction client stay in the same transaction by checking that writes roll back when the transaction fails.

## Summary by CodeRabbit

* **Bug Fixes**
  * Ensures cloned/derived clients preserve the active transaction context so transactional operations behave correctly.

* **Tests**
  * Added end-to-end tests verifying transaction isolation and rollback when using client helper methods inside transactions.

### CODE REVIEW

File: packages/orm/src/client/client-impl.ts [hunk 1]
```diff
@@ -379,6 +378,10 @@ export class ClientImpl {
         newClient.inputValidator = new InputValidator(newClient as any, {
             enabled: newOptions.validateInput !== false,
         });
+        // preserve transaction state so the new client stays in the same transaction
+        if (this.kysely.isTransaction) {
```
Comment (ymc9) [inline packages/orm/src/client/client-impl.ts]: Thanks @pkudinov , this is an important fix!

There're a few other places that need the same care: `$setAuth`, `$setOptions`. I think we can consolidate the change into the constructor. When `baseClient` is passed and `baseClient.kysely` is a transaction, we directly reuse it in the newly constructed client. What do you think?

Comment (pkudinov) [reply packages/orm/src/client/client-impl.ts]: Implemented in `abeac6fb`.

I moved the transaction reuse into the constructor for the non-executor clone path, so `$setAuth` and `$setOptions` are covered automatically alongside `$use`/`$unuse`/`$unuseAll`. The working version was to reuse the transaction through the public accessors (`baseClient.isTransaction` / `baseClient.$qb`) rather than reading private state directly.

I also extended the e2e coverage to include `$setAuth` and `$setOptions`, and updated the `$use` test to use a real `onQuery` hook.

Please let me know what you think @ymc9

Comment (ymc9) [reply packages/orm/src/client/client-impl.ts]: Looks good. I've made a local refactor and pushed a change. Will merge once CI passes.

**Comment by docloulou** [comment]
This fix #2493 ? 
´´´
client.$setAuth(...) returns a new ZenStackClient instance that re-triggers entity mutation hooks, causing infinite recursion when the hook performs mutations on the same model it listens to.
´´´
