### PR TITLE
fix: generate .zenstack with the same level of @zenstackhq

### LINKED ISSUE #462: .zenstack dir is not generated into correct location for pnpm project
Repro: https://github.com/Azzerty23/zenstack-rest-turbo

Run `pnpm zen:up` from the root folder, and you'll find `.zenstack` folder is generated into `/@zenstackhq/runtime/node_modules/`. The reason is pnpm can install packages locally under other packages. After finding the location of `@zenstackhq/runtime` package, I think we need to move up two levels to find the real `node_modules` location.

@jiashengguo

### PR DESCRIPTION
**Pull request by jiashengguo**
fix #462

### CODE REVIEW

File: packages/schema/src/plugins/plugin-utils.ts [hunk 1]
```diff
@@ -25,7 +25,11 @@ export function getNodeModulesFolder(startPath?: string): string | undefined {
  */
 export function getDefaultOutputFolder() {
     // Find the real runtime module path, it might be a symlink in pnpm
-    const runtimeModulePath = require.resolve('@zenstackhq/runtime');
+    let runtimeModulePath = require.resolve('@zenstackhq/runtime');
```
Comment (ymc9) [inline packages/schema/src/plugins/plugin-utils.ts:28]: I think this willl resolve to ".../index.js". We need to get dirname and then walk up?

Comment (ymc9) [reply packages/schema/src/plugins/plugin-utils.ts:28]: > I think this willl resolve to "index.js". We need to get dirname and then walk up?

Maybe safer to check if it's a file? I'm not sure if the resolving behavior is always consistent ... I remember when I tried it's index.js

Comment (jiashengguo) [reply packages/schema/src/plugins/plugin-utils.ts:30]: yes, it is.  changed to use folder name to locate the folder

**Review by ymc9 — APPROVED** [review]
