### PR TITLE
fix: better cli reporting of missing/invalid config file

### LINKED ISSUE #343: CLI should report error when a non-existent config file is specified

### PR DESCRIPTION
**Pull request by potion-cellar**
fixes #343 

 - slightly more granular error reporting for config file issues
 - slightly better test coverage

### CODE REVIEW

File: packages/schema/src/cli/config.ts [hunk 1]
```diff
@@ -19,22 +19,22 @@ export let config: ConfigType = schema.parse({});
...
-        return;
-    }
-
-    let content: unknown;
+export function loadConfig( filename: string ) {
     try {
-        content = JSON.parse(fs.readFileSync(filename, 'utf-8'));
-    } catch {
-        throw new CliError(`Config is not a valid JSON file: ${filename}`);
+        const fileData = fs.readFileSync( filename, `utf-8` );
```
Comment (ymc9) [inline packages/schema/src/cli/config.ts:24]: I see there're extra leading and trailing spaces within parentheses. Did this happen when the code is auto-formatted in VSCode? Not sure if there's any inconsistency in prettier settings between our settings.

Comment (potion-cellar) [reply packages/schema/src/cli/config.ts:24]: Yes it's VSCode doing that specific formatting. I have prettier running but that looks like there is a conflict going on

Comment (potion-cellar) [reply packages/schema/src/cli/config.ts]: Okay I have prettier taking precedence now, looks like that's resolved.
