### PR TITLE
fix(JSON): @default not working for @JSON types & Typed JSON lists generating invalid Zod schemas

### LINKED ISSUE #2039: Strong typed JSON fields don't support @default and generate invalid Zod schemas when they are a List
**Description and expected behavior**
```
type Foo {
    a String
}

model Bar {
    id            String    @id   @default(cuid())
    foo          Foo       @json @default("{ \"a\": \"a\" }")
    fooList    Foo[]    @json @default("[{ \"a\": \"b\" }]")
}
```

@default args on Typed JSON fields currently fail with the error: `Value is not assignable to parameter`
However as per the [Prisma docs](https://www.prisma.io/docs/orm/prisma-client/special-fields-and-types/working-with-json-fields#how-to-set-a-default-value-for-json-fields), strings are the intended method to provide default JSON values.

Unrelated to that, the generated Zod schemas for Typed JSON lists like `fooList` are missing `z.array(...)`, the typescript types are correct

**Environment (please complete the following information):**

-   ZenStack version: 2.12.2
-   Prisma version: 6.4.x
-   Database type: Postgresql

**Additional context**

Raising a PR to address this shortly, just needed an issue number for the regression test :)

### PR DESCRIPTION
**Pull request by diesal11**
Fixes #2039

### CODE REVIEW

File: packages/schema/src/language-server/validator/attribute-application-validator.ts [hunk 1]
```diff
@@ -267,6 +267,12 @@ function assignableToAttributeParam(arg: AttributeArg, param: AttributeParam, at
     if (dstType === 'ContextType') {
         // ContextType is inferred from the attribute's container's type
         if (isDataModelField(attr.$container)) {
+            // If the field is Typed JSON, and the param is @default, the argument must be a string
+            const dstIsTypedJson = attr.$container.attributes.find((attr) => attr.decl.ref?.name === '@json');
```
Comment (ymc9) [inline packages/schema/src/language-server/validator/attribute-application-validator.ts:271]: You can use the `hasAttribute` helper here, to make the code shorter.

**Review by ymc9 — COMMENTED** [review]
Thank you for making the fix @diesal11 ! I've added a minor comments. I'll make the adjustment and release a patch 😄.

**Review by ymc9 — APPROVED** [review]

**Review by ymc9 — APPROVED** [review]
